name: Build Android APK

on:
  push:
    branches:
      - AndroidBuild

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build APK with Docker
        run: |
          docker run --rm \
            -v $GITHUB_WORKSPACE:/home/user/hellfire \
            -w /home/user/hellfire \
            --entrypoint /bin/bash \
            kivy/buildozer \
            -c "echo 'y' | buildozer android debug"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: hellfire-apk
          path: bin/*.apk
